# Generated by Django 2.1.2 on 2018-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField()),
                ('student_age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
